CREATE TABLE IF NOT EXISTS public.pft_users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

ALTER TABLE public.pft_users ENABLE ROW LEVEL SECURITY;
